server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 172.31.241.156:8848
    gateway:
      server:
        webflux:
          routes:
            - id: user
              uri: lb://user-service
              predicates:
                - Path=/user/**
              filters:
                - RewritePath=/user/(?<segment>.*), /${segment}

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: false
                maxAge: 3600
jwt:
  secret: tamakara