spring:
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: 172.31.241.156:8848
    openfeign:
      okhttp:
        enabled: true

server:
  port: 8001

mybatis-plus:
  type-aliases-package: com.bakabooth.user.domain.entity
  mapper-locations: "classpath*:/mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_null