version: '3.7'

services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-server
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql-server
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=0d000721
      - NACOS_AUTH_TOKEN=dGFtYWthcmF0YW1ha2FyYXRhbWFrYXJhdGFtYWthcmE=
      - NACOS_AUTH_IDENTITY_KEY=tamakara
      - NACOS_AUTH_IDENTITY_VALUE=0d000721
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    ports:
      - "8090:8080"
      - "8848:8848"
    volumes:
      - nacos-data:/home/nacos/data
    networks:
      - bakabooth-network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 0d000721
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/nacos.sql:/docker-entrypoint-initdb.d/nacos.sql
    networks:
      - bakabooth-network
    restart: always

volumes:
  nacos-data:
  mysql-data:

networks:
  bakabooth-network:
    driver: bridge
