spring:
  application:
    name: shop-service
  cloud:
    nacos:
      server-addr: 172.31.241.156:8848
    openfeign:
      okhttp:
        enabled: true
  datasource:
    url: jdbc:mysql://172.31.241.156:3306/shop_service_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: shop_service_user
    password: 0d000721
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082

mybatis-plus:
  type-aliases-package: com.bakabooth.shop.domain.entity
  mapper-locations: "classpath*:/mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_null